
// this is commit
//let a = 40
//let b = 9 
//console.log ("a = ", a,"b = ", b,);        
//console.log("a + b = ",a + b);
//console.log("a - b = ",a - b);
//console.log("a * b = ",a * b);
//console.log("a / b = ",a / b);
/* let a = 5 
let b = 9  */
//a += 1 
//b -= 5 
//console.log ("a = ", a,"b = ", b,);  
//console.log (a + b)
//console.log(a<=b )
 
//let age =17

//if (age>=18) {
//    console.log("vote")
//} else {
   // console.log("not vote")
//}
//let age = 

    
//if (age <18 ) {
//    console.log("junior")
//} 
//else (age >60);{
//    console.log("senior")
//} 
//let age = 17
//let result = age > 18 ? "adult": "not adult"
//console.log(result)
//for (let i =1 ;i<=10; i++ ){
  // console.log("vineet singh")
//}
//console.log("loop has ended")
//let sum = 0;
//for (let i = 1; i<=4854;i++){
 //  sum = sum + i
//}
//console.log("sum =",sum)
//let i = 1;
//while (i<=5){
  // console.log("i=", i);
//}
// i = 1
//do {
  //console.log("i=", i);
  //i++;
//let} while (i <=10);
//for-of loop
//let str = "javascript"
//let size = 0
//for (let val of str) {
 // console.log("i=",val);
  //size++;
//}
//console.log("size=",size)
/* dviofeviufvepivrfbiupbn
dvcndiuivhivfiuv */
// strings
/*  str = "vineet singh "let */
/* str = 'vineet singh'
str2 = 'JAVA'
str2.length 
console.log(str2.length);
console.log(str[0]) */
/* let obj = {
 item : "Pen" ,
 price : 150
 
};
let output = `the cost of ${obj.item} is ${obj.price} rupees`;
console.log(output) */
//let str ="vineet singh"
/* let str = "hello"
console.log(str.replace('h',"d")) */
/* let heroes = ["Ironman",'hulk','thor',"Batman"]
let rating = ["4.8",'3.5','4.9','5.0']
let Specialities =["Array of weapons",'gamma rays','gift of forgetfulness','man are brave']
for(let idx=0;idx<heroes.length;idx++){
  console.log(heroes[idx]);
}
for(let idx=0;idx<rating.length;idx++){
  console.log(rating[idx]);
}
for(let idx=0;idx< Specialities.length;idx++){
  console.log( Specialities[idx]);
} */
/* let citys = ['Faridabad','gurgaon','delhi','Banglore']
for (let city of citys){
  console.log(city)
} */
/* let marks =['85','97','44','37','76','60']
fo; ){
  console.log(marks)
}""
 */
/* let items = [250,645,300,900,150]
let i = 0;
for (let val of items){
  console.log(`value at index ${i}=${val}`);
  let offer = val /10;
  items [i] = items [i]-offer;
  console.log(`value after offer =${items[i]}`
  );
  i++;
} */
/* let fooditems = ['potato','apple ','tomato']
/* fooditems.push('chips','paneer') */
//fooditems.pop();
/*  console.log(fooditems) 
console.log(fooditems.toString()); */
/* let marvelheroes  = ["Thor","spiderman","iroman","Dr. strange"]
console.log(marvelheroes.slice(1)); */
/* function myfunction(msg){
  console.log(msg)
}
myfunction(
            "Thor spiderman iroman Dr. strange"
  
  ) */
 /* function sum(x,y){
  console.log(x+y);
/*  } 



  function mul (){
    console.log(a*b); 
  } */

  /*   const arroesum = (a,b) => {
      console.log( a+b )
  } */
  /*     const arroemul = (a,b) => {
        console.log( a/b )
    } */
  /*       const arroemuti = (a,b) => {
          console.log( a*b )
      } */